### ISSUE TITLE
Compare / Contrast JSON API and GraphQL

### ISSUE THREAD

**Issue by undiwahn** [SkywardApps/popcorn#18]
One very obvious question that potential users will have is:

> Why should I use this instead of JSON API or GraphQL?

We should address this head on in the documentation.  

Some points to consider:

- Simplicity (+ for Popcorn)
- Performance in regards to consuming output (Potential + for Popcorn, maybe + for GraphQL too)
- Implementation provided (+ for Popcorn for .net at least!)
- Popcorn can fairly seamlessly integrate with an existing API without changing the schema

We need to provided researched pros and cons.

**Comment by alexbarbato** [comment]
Just jotting down some stuff I'm finding/thinking:

**JSON API:**
It's a standard (that has pluses and minuses)
 + flexibility costs
 + potentially easier to integrate (but that is heavily project dependent)
 + Lots of implementation tools to ease the burden of implementation
Technically, due to the fact that JSON API is a standard, it's a bit correlary to Popcorn as we COULD make popcorn an implementation of JSON API
